services:
  postgres:
    image: postgres:15
    container_name: postgres.local
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  migrate:
    container_name: migrate.local
    build:
      context: ./app/backend
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=postgres.local
      - DB_PORT=5432
      - DB_NAME=sampledb
    entrypoint: ["./main", "migrate"]
    depends_on:
      - postgres
  backend:
    container_name: backend.local
    build:
      context: ./app/backend
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=postgres.local
      - DB_PORT=5432
      - DB_NAME=sampledb
    ports:
      - "8080:8080"
    command: ./main
    depends_on:
      - postgres
      - migrate
  prism:
    image: stoplight/prism:latest
    container_name: prism.local
    ports:
      - "4010:4010"
    volumes:
      - ./app/open-api:/mock
    command: mock -h 0.0.0.0 /mock/openapi.yaml
