version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres.local
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
