openapi: "3.0.3"
info:
  title: simple task api
  description: simple task api
  version: "1.0.0"
servers:
  - url: http://localhost:8000
    description: API Mock Server
  - url: http://localhost:9000
    description: Swagger UI Server
paths:
  /task/{id}:
    $ref: "./paths/task-by-id.yaml"
  /task:
    $ref: "./paths/task.yaml"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TaskRequest:
      $ref: "./components/schemas/task-request.yaml"
    TaskResponse:
      $ref: "./components/schemas/task-response.yaml"
    TaskListResponse:
      $ref: "./components/schemas/task-list-response.yaml"
tags:
  - name: user
    description: ユーザー
  - name: task
    description: タスク
